### ISSUE TITLE
Error on BT connection lost.

### ISSUE THREAD

**Issue by staubsauger** [staubsauger/ChessnutPy#2]
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<ChessnutAir.run() done, defined at /home/rudi/Games/chessnutpy/ChessnutPy/ChessnutAir.py:211> exception=BleakError('Not connected')>
Traceback (most recent call last):
File "/home/rudi/Games/chessnutpy/ChessnutPy/ChessnutAir.py", line 231, in run
await self.game_loop()  # call user game loop
File "/home/rudi/Games/chessnutpy/ChessnutPy/BoardGame.py", line 533, in game_loop
await self.game_loop()
File "/home/rudi/Games/chessnutpy/ChessnutPy/BoardGame.py", line 496, in game_loop
await self.maybe_read_board()
File "/home/rudi/Games/chessnutpy/ChessnutPy/BoardGame.py", line 549, in maybe_read_board
await self.fix_board()
File "/home/rudi/Games/chessnutpy/ChessnutPy/BoardGame.py", line 315, in fix_board
await self.blink_tick(sleep_time=0.3)
File "/home/rudi/Games/chessnutpy/ChessnutPy/ChessnutAir.py", line 66, in blink_tick
await self.change_leds(self.to_blink.union(self.to_light))
File "/home/rudi/Games/chessnutpy/ChessnutPy/ChessnutAir.py", line 140, in change_leds
await self._connection.write_gatt_char(constants.BtCharacteristics.write, self._led_command + arr)
File "/home/rudi/.conda/envs/chessnutpy/lib/python3.10/site-packages/bleak/__init__.py", line 593, in write_gatt_char
await self._backend.write_gatt_char(char_specifier, data, response)
File "/home/rudi/.conda/envs/chessnutpy/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 752, in write_gatt_char
raise BleakError("Not connected")
bleak.exc.BleakError: Not connected

**Comment by BierLiebHaber** [comment]
basic fix with commit [fb9428f](https://github.com/staubsauger/ChessnutPy/commit/fb9428fd8f99b89a7ff88b19fcafe2e9a9074478) tho some strange things may occur when in certain states, requiring a restart
