### ISSUE TITLE
RuntimeError when started with "no_server = true" in config

### ISSUE THREAD

**Issue by staubsauger** [staubsauger/ChessnutPy#3]
Traceback (most recent call last):
  File "/home/rudi/Games/chessnutpy/ChessnutPy/main.py", line 118, in <module>
    asyncio.get_event_loop().close()
  File "/home/rudi/Games/chessnutpy/ChessnutPy/.conda/lib/python3.10/site-packages/chess/engine.py", line 92, in get_event_loop
    raise RuntimeError(f"no current event loop in thread {threading.current_thread().name!r}")
RuntimeError: no current event loop in thread 'MainThread'

**Comment by BierLiebHaber** [comment]
fixed by [ae76380](https://github.com/staubsauger/ChessnutPy/commit/ae7638008e2d96e9c9caae9c96f35e4e6c4912da)
