### ISSUE TITLE
when starting the pi, with the board turned off

### ISSUE THREAD

**Issue by staubsauger** [staubsauger/ChessnutPy#6]
2023-10-18_22:34:31.00607 Traceback (most recent call last):
2023-10-18_22:34:31.01101   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 246, in run
2023-10-18_22:34:31.01107     await self.game_loop()  # call user game loop
2023-10-18_22:34:31.01109     ^^^^^^^^^^^^^^^^^^^^^^
2023-10-18_22:34:31.01156   File "/home/chess/chessnut/ChessnutPy/BoardGame.py", line 500, in game_loop
2023-10-18_22:34:31.01159     await self.maybe_read_board()
2023-10-18_22:34:31.01189   File "/home/chess/chessnut/ChessnutPy/BoardGame.py", line 553, in maybe_read_board
2023-10-18_22:34:31.01192     await self.fix_board()
2023-10-18_22:34:31.01222   File "/home/chess/chessnut/ChessnutPy/BoardGame.py", line 318, in fix_board
2023-10-18_22:34:31.01225     await self.blink_tick(sleep_time=0.3)
2023-10-18_22:34:31.01255   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 71, in blink_tick
2023-10-18_22:34:31.01267     await self.change_leds(self.to_blink.union(self.to_light))
2023-10-18_22:34:31.01297   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 155, in change_leds
2023-10-18_22:34:31.01300     await self._connection.write_gatt_char(constants.BtCharacteristics.write, self._led_command + arr)
2023-10-18_22:34:31.01333   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/bleak/__init__.py", line 593, in write_gatt_char
2023-10-18_22:34:31.01339     await self._backend.write_gatt_char(char_specifier, data, response)
2023-10-18_22:34:31.01369   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 752, in write_gatt_char
2023-10-18_22:34:31.01372     raise BleakError("Not connected")
2023-10-18_22:34:31.01412 bleak.exc.BleakError: Not connected
2023-10-18_22:34:31.01492
2023-10-18_22:34:31.01495 During handling of the above exception, another exception occurred:
2023-10-18_22:34:31.01501
2023-10-18_22:34:31.01533 Traceback (most recent call last):
2023-10-18_22:34:31.01764   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 102, in connect
2023-10-18_22:34:31.01768     await self.discover()
2023-10-18_22:34:31.01801   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 91, in discover
2023-10-18_22:34:31.01804     await BleakScanner.find_device_by_filter(
2023-10-18_22:34:31.01841   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/bleak/__init__.py", line 323, in find_device_by_filter
2023-10-18_22:34:31.01850     async with cls(detection_callback=apply_filter, **kwargs):
2023-10-18_22:34:31.01880   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/bleak/__init__.py", line 126, in __aenter__
2023-10-18_22:34:31.01883     await self._backend.start()
2023-10-18_22:34:31.01913   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 179, in start
2023-10-18_22:34:31.01920     adapter_path = manager.get_default_adapter()
2023-10-18_22:34:31.01922                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18_22:34:31.01952   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 299, in get_default_adapter
2023-10-18_22:34:31.01955     raise BleakError("No Bluetooth adapters found.")
2023-10-18_22:34:31.01993 bleak.exc.BleakError: No Bluetooth adapters found.
2023-10-18_22:34:31.02033
2023-10-18_22:34:31.02035 During handling of the above exception, another exception occurred:
2023-10-18_22:34:31.02037
2023-10-18_22:34:31.02067 Traceback (most recent call last):
2023-10-18_22:34:31.02300   File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
2023-10-18_22:34:31.02305     msg = self.format(record)
2023-10-18_22:34:31.02307           ^^^^^^^^^^^^^^^^^^^
2023-10-18_22:34:31.02340   File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
2023-10-18_22:34:31.02348     return fmt.format(record)
2023-10-18_22:34:31.02350            ^^^^^^^^^^^^^^^^^^
2023-10-18_22:34:31.02380   File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
2023-10-18_22:34:31.02383     record.message = record.getMessage()
2023-10-18_22:34:31.02385                      ^^^^^^^^^^^^^^^^^^^
2023-10-18_22:34:31.02414   File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
2023-10-18_22:34:31.02417     msg = msg % self.args
2023-10-18_22:34:31.02423           ~~~~^~~~~~~~~~~
2023-10-18_22:34:31.02459 TypeError: not all arguments converted during string formatting
2023-10-18_22:34:31.02496 Call stack:
2023-10-18_22:34:31.04380   File "/home/chess/chessnut/ChessnutPy/main.py", line 104, in <module>
2023-10-18_22:34:31.04386     web.run_app(go(), host=hosts, port=options.port)
2023-10-18_22:34:31.04415   File "/home/chess/chessnut/ChessnutPy/chess-env/lib/python3.11/site-packages/aiohttp/web.py", line 516, in run_app
2023-10-18_22:34:31.04433     loop.run_until_complete(main_task)
2023-10-18_22:34:31.04459   File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
2023-10-18_22:34:31.04462     self.run_forever()
2023-10-18_22:34:31.04486   File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
2023-10-18_22:34:31.04489     self._run_once()
2023-10-18_22:34:31.04513   File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
2023-10-18_22:34:31.04516     handle._run()
2023-10-18_22:34:31.04544   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
2023-10-18_22:34:31.04547     self._context.run(self._callback, *self._args)
2023-10-18_22:34:31.04572   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 252, in run
2023-10-18_22:34:31.04574     await self.connect() # <- loops until connection
2023-10-18_22:34:31.04599   File "/home/chess/chessnut/ChessnutPy/ChessnutAir.py", line 107, in connect
2023-10-18_22:34:31.04602     log.warning("BleakError during connect: ", e)
2023-10-18_22:34:31.04644 Message: 'BleakError during connect: '
2023-10-18_22:34:31.04647 Arguments: (BleakError('No Bluetooth adapters found.'),)
2023-10-18_22:34:34.75366 Config File (/home/chess/.config/chessnutair.config):
2023-10-18_22:34:34.75388   engine_cmd:        lc0
2023-10-18_22:34:34.75390   engine_cfg:        {'WeightsFile' : "/home/chess/chessnut/lc0-weights/maia-1100.pb.gz"}
2023-10-18_22:34:34.75392   suggestion_book_dir:./Docs/Elo2400.bin
2023-10-18_22:34:34.75394   engine_time:       0.5
2023-10-18_22:34:34.75407   engine_depth:      None
2023-10-18_22:34:34.75409   engine_nodes:      1
2023-10-18_22:34:34.75411   no_suggestions:    false
2023-10-18_22:34:34.75413   engine_suggest_cmd:stockfish
2023-10-18_22:34:34.75415   eco_file:          ./Docs/scid.eco
2023-10-18_22:34:34.75416   sug_time:          5.0
2023-10-18_22:34:34.75418   sug_depth:         None
2023-10-18_22:34:34.75420   sug_nodes:         None
2023-10-18_22:34:34.75422   show_would_have_done_move:false
2023-10-18_22:34:34.75455   experimental_dragging_detection:true
2023-10-18_22:34:34.75457   experimental_dragging_timeout:0.3
2023-10-18_22:34:34.75459   play_animations:   true
2023-10-18_22:34:34.75461   show_valid_moves:  false
2023-10-18_22:34:34.75463   no_server:         false
2023-10-18_22:34:34.75465   hosts:             auto-hosts
2023-10-18_22:34:34.75467   port:              8080
2023-10-18_22:34:34.75468   lichess_token:
2023-10-18_22:34:34.75470   logfile:           /userdata/logs/chessnutpy/game.log
2023-10-18_22:34:34.75476 Config File (./Docs/default.config):
2023-10-18_22:34:34.75478   no_suggestions:    false
2023-10-18_22:34:34.75480   show_would_have_done_move:false
2023-10-18_22:34:34.75482   show_valid_moves:  false
2023-10-18_22:34:34.75483   no_server:         false
2023-10-18_22:34:34.75485 192.168.1.103
2023-10-18_22:34:34.75487 ======== Running on http://192.168.1.103:8080, http://localhost:8080 ========
2023-10-18_22:34:34.75507 (Press CTRL+C to quit)

**Comment by BierLiebHaber** [comment]
`TypeError: not all arguments converted during string formatting`
which seems to be the relevant error should be fixed by [dc5bac3](https://github.com/staubsauger/ChessnutPy/commit/dc5bac31bc50cce695834b856b914025bf72c066)
